# =========================================
# G-SCHOOLS EMS — GOTIFY SERVER CONFIG
# =========================================

server:
  # Bind to all network interfaces
  listenaddr: ""
  port: 80

  ssl:
    enabled: false  # Render already terminates HTTPS for you
    redirecttohttps: true
    listenaddr: ""
    port: 443
    certfile: ""
    certkey: ""
    letsencrypt:
      enabled: false
      accepttos: false
      cache: data/certs
      directoryurl: ""
      hosts: []

  responseheaders:
    X-Frame-Options: "DENY"
    X-Content-Type-Options: "nosniff"
    Referrer-Policy: "no-referrer"

  trustedproxies:
    - 127.0.0.1/32
    - ::1

  cors:
    alloworigins:
      - "https://server-auud.onrender.com"
      - "http://localhost"
    allowmethods:
      - "GET"
      - "POST"
    allowheaders:
      - "Authorization"
      - "content-type"

  stream:
    pingperiodseconds: 45
    allowedorigins:
      - "https://server-auud.onrender.com"
      - "http://localhost"

database:
  dialect: sqlite3
  connection: data/gotify.db

defaultuser:
  name: admin
  pass: adminpassword123  # <-- change this!

passstrength: 10
uploadedimagesdir: data/images
pluginsdir: data/plugins
registration: false
keepaliveperiodseconds: 0