# ===========================================
# Gotify Render Deployment Configuration
# ===========================================

services:
  - type: web
    name: gotify
    env: docker
    plan: free
    region: oregon           # Or another region close to you
    dockerfilePath: ./Dockerfile
    envVars:
      - key: GOTIFY_SERVER_PORT
        value: 80
    healthCheckPath: /
    autoDeploy: true
